/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./CWAdminFactory.client";
import * as _3 from "./CWCore.client";
import * as _5 from "./CWNamedGroups.client";
import * as _7 from "./CWNamesRegistry.client";
import * as _9 from "./CWNativeStakedBalanceVoting.client";
import * as _11 from "./CWProposalMultiple.client";
import * as _13 from "./CWProposalSingle.client";
import * as _15 from "./CWTokenSwap.client";
import * as _17 from "./CW4Voting.client";
import * as _19 from "./Profiles.client";
export declare namespace contracts {
    const CWAdminFactory: {
        CWAdminFactoryClient: typeof _1.CWAdminFactoryClient;
    };
    const CWCore: {
        CWCoreQueryClient: typeof _3.CWCoreQueryClient;
        CWCoreClient: typeof _3.CWCoreClient;
    };
    const CWNamedGroups: {
        CWNamedGroupsQueryClient: typeof _5.CWNamedGroupsQueryClient;
        CWNamedGroupsClient: typeof _5.CWNamedGroupsClient;
    };
    const CWNamesRegistry: {
        CWNamesRegistryQueryClient: typeof _7.CWNamesRegistryQueryClient;
        CWNamesRegistryClient: typeof _7.CWNamesRegistryClient;
    };
    const CWNativeStakedBalanceVoting: {
        CWNativeStakedBalanceVotingQueryClient: typeof _9.CWNativeStakedBalanceVotingQueryClient;
        CWNativeStakedBalanceVotingClient: typeof _9.CWNativeStakedBalanceVotingClient;
    };
    const CWProposalMultiple: {
        CWProposalMultipleQueryClient: typeof _11.CWProposalMultipleQueryClient;
        CWProposalMultipleClient: typeof _11.CWProposalMultipleClient;
    };
    const CWProposalSingle: {
        CWProposalSingleQueryClient: typeof _13.CWProposalSingleQueryClient;
        CWProposalSingleClient: typeof _13.CWProposalSingleClient;
    };
    const CWTokenSwap: {
        CWTokenSwapQueryClient: typeof _15.CWTokenSwapQueryClient;
        CWTokenSwapClient: typeof _15.CWTokenSwapClient;
    };
    const CW4Voting: {
        CW4VotingQueryClient: typeof _17.CW4VotingQueryClient;
        CW4VotingClient: typeof _17.CW4VotingClient;
    };
    const Profiles: {
        ProfilesQueryClient: typeof _19.ProfilesQueryClient;
        ProfilesClient: typeof _19.ProfilesClient;
    };
}
