/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CWAdminFactory.types";
import * as _1 from "./CWAdminFactory.client";
import * as _2 from "./CWCore.types";
import * as _3 from "./CWCore.client";
import * as _4 from "./CWNamedGroups.types";
import * as _5 from "./CWNamedGroups.client";
import * as _6 from "./CWNamesRegistry.types";
import * as _7 from "./CWNamesRegistry.client";
import * as _8 from "./CWNativeStakedBalanceVoting.types";
import * as _9 from "./CWNativeStakedBalanceVoting.client";
import * as _10 from "./CWProposalMultiple.types";
import * as _11 from "./CWProposalMultiple.client";
import * as _12 from "./CWProposalSingle.types";
import * as _13 from "./CWProposalSingle.client";
import * as _14 from "./CWTokenSwap.types";
import * as _15 from "./CWTokenSwap.client";
import * as _16 from "./CW4Voting.types";
import * as _17 from "./CW4Voting.client";
import * as _18 from "./Profiles.types";
import * as _19 from "./Profiles.client";
export namespace contracts {
  export const CWAdminFactory = { ..._0,
    ..._1
  };
  export const CWCore = { ..._2,
    ..._3
  };
  export const CWNamedGroups = { ..._4,
    ..._5
  };
  export const CWNamesRegistry = { ..._6,
    ..._7
  };
  export const CWNativeStakedBalanceVoting = { ..._8,
    ..._9
  };
  export const CWProposalMultiple = { ..._10,
    ..._11
  };
  export const CWProposalSingle = { ..._12,
    ..._13
  };
  export const CWTokenSwap = { ..._14,
    ..._15
  };
  export const CW4Voting = { ..._16,
    ..._17
  };
  export const Profiles = { ..._18,
    ..._19
  };
}